# Session 3
## Experiment 1
###  Lab Overview
1. Feature Selection


### Objective

To understand **Feature Selection**

Let us revisit the IRIS dataset for this task. The dataset has 3 classes and 4 features. 


### Data Source
https://archive.ics.uci.edu/ml/datasets/iris


#### Dataset Information:

IRIS_Dataset is perhaps the best known database to be found in the pattern recognition literature. Fisher's paper is a classic in the field and is referenced frequently to this day. 

The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant. One class is linearly separable from the other 2; the latter are NOT linearly separable from each other. 


### Data Attributes

  1. sepal length in cm 
  2. sepal width in cm 
  3. petal length in cm 
  4. petal width in cm 
  5. class: 
     - Iris Setosa  
     - Iris Versicolour 
     - Iris Virginica


## Feature Selection

In [2]:
###Load the Dataset
import pandas as pd
pd.read_csv("bezdekIris.data", header=None)

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa
24   4.8  3.4  1.9  0.2     Iris-setosa
25   5.0  3.0  1.6  0.2     Iris-setosa
26   5.0  3.4  1.6  0.4     Iris-setosa
27   5.2  3.5  1.5  0.2     Iris-setosa
28   5.2  3.4  1.4  0.2     Iris-setosa
29   4.7  3.2  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
120  6.9  3.2  5.7  2.3  Iris-virginica
121  5.6  2.8  4.9  2.0  Iris-virginica
122  7.7  2.8  6.7  2.0  Iris-virginica
123  6.3  2.7  4.9  1.8  Iris-virginica
124  6.7  3.3  5.7  2.1  Iris-virginica
125  7.2  3.2  6.0  1.8  Iris-virginica
126  6.2  2.8  4.8  1.8  Iris-virginica
127  6.1  3.0  4.9  1.8  Iris-virginica
128  6.4  2.8  5.6  2.1  Iris-virginica
129  7.2  3.0  5.8  1.6  Iris-virginica
130  7.4  2.8  6.1  1.9  Iris-virginica
131  7.9  3.8  6.4  2.0  Iris-virginica
132  6.4  2.8  5.6  2.2  Iris-virginica
133  6.3  2.8  5.1  1.5  Iris-virginica
134  6.1  2.6  5.6  1.4  Iris-virginica
135  7.7  3.0  6.1  2.3  Iris-virginica
136  6.3  3.4  5.6  2.4  Iris-virginica
137  6.4  3.1  5.5  1.8  Iris-virginica
138  6.0  3.0  4.8  1.8  Iris-virginica
139  6.9  3.1  5.4  2.1  Iris-virginica
140  6.7  3.1  5.6  2.4  Iris-virginica
141  6.9  3.1  5.1  2.3  Iris-virginica
142  5.8  2.7  5.1  1.9  Iris-virginica
143  6.8  3.2  5.9  2.3  Iris-virginica
144  6.7  3.3  5.7  2.5  Iris-virginica
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
### Convert the labels column as 0 for "iris-setosa", 1 for "iris-versicolor" and 2 for "iris-virginica"  
### Store the converted data in variable iris_data
def irisLabel(s):
    s = s.lower()
    if s == "iris-setosa":
        return 0
    if s == "iris-versicolor":
        return 1
    if s == "iris-virginica":
        return 2
    
import pandas as pd
iris_data = pd.read_csv("bezdekIris.data",header=None, converters={4:irisLabel})
iris_data

0    1    2    3  4
0    5.1  3.5  1.4  0.2  0
1    4.9  3.0  1.4  0.2  0
2    4.7  3.2  1.3  0.2  0
3    4.6  3.1  1.5  0.2  0
4    5.0  3.6  1.4  0.2  0
5    5.4  3.9  1.7  0.4  0
6    4.6  3.4  1.4  0.3  0
7    5.0  3.4  1.5  0.2  0
8    4.4  2.9  1.4  0.2  0
9    4.9  3.1  1.5  0.1  0
10   5.4  3.7  1.5  0.2  0
11   4.8  3.4  1.6  0.2  0
12   4.8  3.0  1.4  0.1  0
13   4.3  3.0  1.1  0.1  0
14   5.8  4.0  1.2  0.2  0
15   5.7  4.4  1.5  0.4  0
16   5.4  3.9  1.3  0.4  0
17   5.1  3.5  1.4  0.3  0
18   5.7  3.8  1.7  0.3  0
19   5.1  3.8  1.5  0.3  0
20   5.4  3.4  1.7  0.2  0
21   5.1  3.7  1.5  0.4  0
22   4.6  3.6  1.0  0.2  0
23   5.1  3.3  1.7  0.5  0
24   4.8  3.4  1.9  0.2  0
25   5.0  3.0  1.6  0.2  0
26   5.0  3.4  1.6  0.4  0
27   5.2  3.5  1.5  0.2  0
28   5.2  3.4  1.4  0.2  0
29   4.7  3.2  1.6  0.2  0
..   ...  ...  ...  ... ..
120  6.9  3.2  5.7  2.3  2
121  5.6  2.8  4.9  2.0  2
122  7.7  2.8  6.7  2.0  2
123  6.3  2.7  4.9  1.8  2
124  6.7  3.3  5.7  2.1  2
125  7.2  3.2  6.0  1.8  2
126  6.2  2.8  4.8  1.8  2
127  6.1  3.0  4.9  1.8  2
128  6.4  2.8  5.6  2.1  2
129  7.2  3.0  5.8  1.6  2
130  7.4  2.8  6.1  1.9  2
131  7.9  3.8  6.4  2.0  2
132  6.4  2.8  5.6  2.2  2
133  6.3  2.8  5.1  1.5  2
134  6.1  2.6  5.6  1.4  2
135  7.7  3.0  6.1  2.3  2
136  6.3  3.4  5.6  2.4  2
137  6.4  3.1  5.5  1.8  2
138  6.0  3.0  4.8  1.8  2
139  6.9  3.1  5.4  2.1  2
140  6.7  3.1  5.6  2.4  2
141  6.9  3.1  5.1  2.3  2
142  5.8  2.7  5.1  1.9  2
143  6.8  3.2  5.9  2.3  2
144  6.7  3.3  5.7  2.5  2
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2

[150 rows x 5 columns]

## Worked Example

Let $X$ be the two class IRIS Dataset. Let $A$ be a $2 \times 4$ matrix as given below:

\begin{equation*}
A=
\begin{bmatrix}
   1 & 0 & 0 & 0\\
   0 & 1 & 0 & 0\\
\end{bmatrix}
\end{equation*}

 
 1. Compute $X' = AX$.
 2. Plot this $X'$ on 2D graph 

In [4]:
#Import required packages
import numpy as np
import matplotlib.pyplot as plt

#Extract features and labels in separate variables
Features = iris_data.iloc[:,0:4].values
Labels = iris_data.iloc[:,4:5].values
print(Features)
print(Labels)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
## Now store Feature matrix as X
X = Features

## Create matrix A as given in the Exercise above
A = np.array([[1,0,0,0],[0,1,0,0]])
print(A)

[[1 0 0 0]
 [0 1 0 0]]


In [6]:
## As A is 2*4 matrix. To compute X' convert X into 4*150 using transpose function. 
##As for matrix multiplication dimensions should match
X_transpose = np.transpose(X)
print(X_transpose)

[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
  3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
  3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
  2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
  2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
  2.6 3.  2.

In [ ]:
## Compute X' same as X1. Only the name is changed. X1 is now 2*150 dimensional.
## Meaning we have extracted 2 features out of 4
###################
## X1 = np.matmul(A,X_transpose)
## Python3 has a new symbol for matrix multiplications
###################
X1 = A @ X_transpose
print(X1.shape)

In [ ]:
## Convert the matrix X1 back to 150*2 and append label creating X1_final of 150*3
X1 = np.transpose(X1)
X1_final = np.hstack((X1,Labels))
print(X1_final)

#### Putting it all together

In [ ]:
## Now store Feature matrix as X
X = Features

## Create matrix A as given in the Exercise above
A = np.array([[1,0,0,0],[0,0,0,1]])

## As A is 2*4 matrix. To compute X' convert X into 4*150 using transpose function. 
##As for matrix multiplication dimensions should match
X_transpose = np.transpose(X)

## Compute X' same as X1. Only the name is changed. X1 is now 2*150 dimensional.
## Meaning we have extracted 2 features out of 4
X1 = A @ X_transpose

## Convert the matrix X1 back to 150*2 and append label creating X1_final of 150*3
X1 = np.transpose(X1)
X1_final = np.hstack((X1,Labels))

##Plot the points on graph and visualize.
plt.figure(1, figsize=(20,10))
plt.scatter(X1_final[:,0],X1_final[:,1],c=X1_final[:,2],s=60)
plt.show()

# Exercise 1
Repeat the above Example with a new matrix A, given below;

\begin{equation*}
A2 =
\begin{bmatrix}
   0 & 1 & 0 & 0\\
   0 & 0 & 1 & 0\\
\end{bmatrix}
\end{equation*}

 1. Compute $X^{\prime} = AX$ ? 
 2. Plot this X on 2D graph.

In [ ]:
### Your code here


# Exercise 2
Repeat the above Example with a new matrix A, given below;
\begin{equation*}
A3 = 
\begin{bmatrix}
   0 & 0 & 1 & 0\\
   0 & 0 & 0 & 1\\
\end{bmatrix}
\end{equation*}
 1. Compute $X^{\prime} = AX$ ? 
 2. Plot this X on 2D graph.

In [ ]:
### Your code here

# Exercise 3

Of the 6 possible projection matrices we have tried out 3. Try out the other three also.


In [ ]:
### 

In [ ]:
###

In [ ]:
###

## Note
$A$ is selecting 2 features to plot Iris Dataset. $A$ is $2 \times 4$ matrix where 2 means number of features you want and 4 means total number of features in Dataset. 

** Question:** Arrange the 6 matrices, in order of separability